import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function futureDate(daysFromNow: number, hour: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, 0, 0, 0);
  return d;
}

const events = [
  {
    name: "Surfers Paradise Beachfront Markets",
    description:
      "Discover handmade crafts, local art, jewellery, and food stalls along the iconic Surfers Paradise beachfront every Wednesday, Friday, and Sunday night. Over 100 stalls lit by fairy lights with live entertainment.",
    startDate: futureDate(2, 17),
    endDate: futureDate(2, 21),
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80",
    url: "https://www.surfersparadise.com/things-to-do/surfers-paradise-beachfront-markets",
    venueName: "Surfers Paradise Beachfront",
    venueAddress: "The Esplanade, Surfers Paradise QLD 4217",
    city: "Gold Coast",
    state: "QLD",
    category: "MARKETS" as const,
    tags: ["markets", "beachfront", "handmade", "night markets"],
    isFree: true,
    source: "seed",
    sourceId: "seed-001",
  },
  {
    name: "Live at Burleigh Pavilion: Friday Sessions",
    description:
      "The Gold Coast's best oceanfront live music venue. This Friday features local indie and electronic acts with sunset views over Burleigh Beach. Full bar and kitchen open.",
    startDate: futureDate(4, 18),
    endDate: futureDate(4, 23),
    imageUrl: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
    url: "https://burleighpavilion.com.au",
    venueName: "Burleigh Pavilion",
    venueAddress: "43 Goodwin Terrace, Burleigh Heads QLD 4220",
    city: "Gold Coast",
    state: "QLD",
    category: "MUSIC" as const,
    tags: ["live music", "nightlife", "oceanfront", "indie"],
    isFree: false,
    priceMin: 15,
    priceMax: 35,
    ticketUrl: "https://burleighpavilion.com.au/whats-on",
    source: "seed",
    sourceId: "seed-002",
  },
  {
    name: "HOTA Gallery: Contemporary Australian Art Exhibition",
    description:
      "Explore the latest rotating exhibition at the Home of the Arts gallery featuring bold works from Queensland and national contemporary artists. Free entry to the main gallery.",
    startDate: futureDate(1, 10),
    endDate: futureDate(30, 17),
    imageUrl: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800&q=80",
    url: "https://hota.com.au",
    venueName: "HOTA - Home of the Arts",
    venueAddress: "135 Bundall Rd, Surfers Paradise QLD 4217",
    city: "Gold Coast",
    state: "QLD",
    category: "ARTS" as const,
    tags: ["art", "gallery", "contemporary", "free entry"],
    isFree: true,
    source: "seed",
    sourceId: "seed-003",
  },
  {
    name: "Miami Marketta Street Food & Live Music",
    description:
      "The Gold Coast's original street food market. Over 30 food vendors from around the world, craft beer, cocktails, and 3 stages of live music. Open Wednesday to Saturday nights.",
    startDate: futureDate(3, 17),
    endDate: futureDate(3, 23),
    imageUrl: "https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800&q=80",
    url: "https://miamimarketta.com",
    venueName: "Miami Marketta",
    venueAddress: "23 Hillcrest Parade, Miami QLD 4220",
    city: "Gold Coast",
    state: "QLD",
    category: "FOOD_DRINK" as const,
    tags: ["street food", "live music", "markets", "nightlife"],
    isFree: false,
    priceMin: 5,
    priceMax: 5,
    source: "seed",
    sourceId: "seed-004",
  },
  {
    name: "Gold Coast Marathon 2026",
    description:
      "Australia's premier road race and one of the world's Top Gold Label marathons. Choose from full marathon, half marathon, 10km, 5.7km, or 2km Junior Dash along the beautiful Gold Coast beachfront.",
    startDate: futureDate(60, 6),
    endDate: futureDate(60, 14),
    imageUrl: "https://images.unsplash.com/photo-1513593771513-7b58b6c4af38?w=800&q=80",
    url: "https://goldcoastmarathon.com.au",
    venueName: "Broadwater Parklands",
    venueAddress: "Marine Parade, Southport QLD 4215",
    city: "Gold Coast",
    state: "QLD",
    category: "SPORTS" as const,
    tags: ["marathon", "running", "fitness", "beachfront"],
    isFree: false,
    priceMin: 45,
    priceMax: 180,
    ticketUrl: "https://goldcoastmarathon.com.au/enter",
    source: "seed",
    sourceId: "seed-005",
  },
  {
    name: "Currumbin Wildlife Sanctuary: Night Zoo",
    description:
      "Experience the magic of the sanctuary after dark. Guided torch-lit tours to see nocturnal animals, koala encounters, live Aboriginal performances, and campfire storytelling for the whole family.",
    startDate: futureDate(7, 18),
    endDate: futureDate(7, 21),
    imageUrl: "https://images.unsplash.com/photo-1459262838948-3e2de6c1ec80?w=800&q=80",
    url: "https://currumbinsanctuary.com.au",
    venueName: "Currumbin Wildlife Sanctuary",
    venueAddress: "28 Tomewin St, Currumbin QLD 4223",
    city: "Gold Coast",
    state: "QLD",
    category: "FAMILY" as const,
    tags: ["family", "kids", "wildlife", "nocturnal"],
    isFree: false,
    priceMin: 55,
    priceMax: 89,
    ticketUrl: "https://currumbinsanctuary.com.au/tickets",
    source: "seed",
    sourceId: "seed-006",
  },
  {
    name: "Stand-Up Comedy at The Star Gold Coast",
    description:
      "A night of belly laughs featuring top Australian comedians at The Star's intimate theatre. Lineup includes local favourites and touring national acts. Licensed bar with pre-show dining available.",
    startDate: futureDate(10, 20),
    endDate: futureDate(10, 22),
    imageUrl: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800&q=80",
    url: "https://www.star.com.au/goldcoast",
    venueName: "The Star Gold Coast",
    venueAddress: "1 Casino Dr, Broadbeach QLD 4218",
    city: "Gold Coast",
    state: "QLD",
    category: "COMEDY" as const,
    tags: ["comedy", "stand-up", "nightlife", "entertainment"],
    isFree: false,
    priceMin: 35,
    priceMax: 65,
    ticketUrl: "https://www.star.com.au/goldcoast/entertainment",
    source: "seed",
    sourceId: "seed-007",
  },
  {
    name: "Bleach* Festival: Ocean & Art",
    description:
      "The Gold Coast's signature arts festival celebrating the intersection of ocean culture and creative expression. Theatre, dance, music, visual art installations across beachfront venues.",
    startDate: futureDate(14, 10),
    endDate: futureDate(21, 22),
    imageUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    url: "https://bleachfestival.com.au",
    venueName: "Various Gold Coast Venues",
    venueAddress: "Gold Coast QLD",
    city: "Gold Coast",
    state: "QLD",
    category: "FESTIVAL" as const,
    tags: ["festival", "arts", "ocean", "dance", "theatre"],
    isFree: false,
    priceMin: 0,
    priceMax: 80,
    source: "seed",
    sourceId: "seed-008",
  },
  {
    name: "Tallebudgera Creek Kayak & SUP Sunset Tour",
    description:
      "Guided sunset paddle through the crystal-clear waters of Tallebudgera Creek. See stingrays, fish, and birdlife while the sun sets over the hinterland. Equipment and instructor included.",
    startDate: futureDate(5, 16),
    endDate: futureDate(5, 18),
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    url: "https://example.com/tallebudgera-paddle",
    venueName: "Tallebudgera Creek",
    venueAddress: "Tallebudgera Creek Rd, Tallebudgera QLD 4228",
    city: "Gold Coast",
    state: "QLD",
    category: "OUTDOOR" as const,
    tags: ["kayak", "SUP", "sunset", "nature", "outdoor"],
    isFree: false,
    priceMin: 65,
    priceMax: 85,
    source: "seed",
    sourceId: "seed-009",
  },
  {
    name: "Gold Coast Titans vs Brisbane Broncos",
    description:
      "NRL derby day! Watch the Gold Coast Titans take on cross-city rivals the Brisbane Broncos at Cbus Super Stadium. Gates open 2 hours before kick-off with food trucks and live entertainment.",
    startDate: futureDate(12, 19),
    endDate: futureDate(12, 21),
    imageUrl: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    url: "https://www.titans.com.au",
    venueName: "Cbus Super Stadium",
    venueAddress: "Centreline Pl, Robina QLD 4226",
    city: "Gold Coast",
    state: "QLD",
    category: "SPORTS" as const,
    tags: ["NRL", "rugby league", "Titans", "Broncos", "derby"],
    isFree: false,
    priceMin: 25,
    priceMax: 120,
    ticketUrl: "https://www.titans.com.au/tickets",
    source: "seed",
    sourceId: "seed-010",
  },
  {
    name: "Cavill Avenue Block Party: DJ Night",
    description:
      "Saturday night block party in the heart of Surfers Paradise. DJs, neon lights, street performers, food trucks, and the energy of Cavill Avenue after dark. 18+ event.",
    startDate: futureDate(6, 21),
    endDate: futureDate(7, 2),
    imageUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80",
    venueName: "Cavill Avenue",
    venueAddress: "Cavill Ave, Surfers Paradise QLD 4217",
    city: "Gold Coast",
    state: "QLD",
    category: "NIGHTLIFE" as const,
    tags: ["nightlife", "DJ", "party", "surfers paradise"],
    isFree: true,
    source: "seed",
    sourceId: "seed-011",
  },
  {
    name: "Springbrook National Park: Guided Glow Worm Night Walk",
    description:
      "Discover the enchanting glow worms of Springbrook's Natural Bridge cave. Expert-guided night walk through ancient rainforest with astronomy stop. Family-friendly, torches provided.",
    startDate: futureDate(8, 19),
    endDate: futureDate(8, 21),
    imageUrl: "https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800&q=80",
    url: "https://example.com/springbrook-glowworms",
    venueName: "Springbrook National Park",
    venueAddress: "Springbrook Rd, Springbrook QLD 4213",
    city: "Gold Coast",
    state: "QLD",
    category: "OUTDOOR" as const,
    tags: ["glow worms", "nature", "family", "night walk", "rainforest"],
    isFree: false,
    priceMin: 40,
    priceMax: 60,
    source: "seed",
    sourceId: "seed-012",
  },
  {
    name: "Broadbeach Jazz Weekend",
    description:
      "Three days of free jazz across multiple stages in Broadbeach. Local and interstate jazz, blues, and soul artists. Restaurants and bars along the strip offer special menus.",
    startDate: futureDate(20, 12),
    endDate: futureDate(22, 22),
    imageUrl: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    url: "https://broadbeachjazz.com",
    venueName: "Broadbeach Mall & Surrounds",
    venueAddress: "Victoria Ave, Broadbeach QLD 4218",
    city: "Gold Coast",
    state: "QLD",
    category: "MUSIC" as const,
    tags: ["jazz", "free", "festival", "broadbeach"],
    isFree: true,
    source: "seed",
    sourceId: "seed-013",
  },
  {
    name: "Carrara Markets: Weekend Bargain Hunt",
    description:
      "Queensland's largest permanent market with over 500 stalls! Fresh produce, fashion, homewares, electronics, and everything in between. Open Saturday and Sunday mornings.",
    startDate: futureDate(3, 7),
    endDate: futureDate(3, 13),
    imageUrl: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
    url: "https://carraramarkets.com.au",
    venueName: "Carrara Markets",
    venueAddress: "Gooding Dr, Carrara QLD 4211",
    city: "Gold Coast",
    state: "QLD",
    category: "MARKETS" as const,
    tags: ["markets", "bargain", "weekend", "family"],
    isFree: true,
    source: "seed",
    sourceId: "seed-014",
  },
  {
    name: "Brisbane Valley Hot Air Ballooning",
    description:
      "Float above the stunning Gold Coast hinterland at sunrise. 60-minute flight over vineyards, farmland, and mountains followed by champagne breakfast. Breathtaking photo opportunities.",
    startDate: futureDate(9, 5),
    endDate: futureDate(9, 9),
    imageUrl: "https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=800&q=80",
    venueName: "Gold Coast Hinterland",
    venueAddress: "Canungra QLD 4275",
    city: "Gold Coast",
    state: "QLD",
    category: "OUTDOOR" as const,
    tags: ["hot air balloon", "sunrise", "hinterland", "romantic"],
    isFree: false,
    priceMin: 290,
    priceMax: 380,
    source: "seed",
    sourceId: "seed-015",
  },
  {
    name: "Community Yoga on the Beach",
    description:
      "Free community yoga session on Kurrawa Beach every Saturday morning. All levels welcome. Bring your own mat. Led by local instructors with ocean sounds as your soundtrack.",
    startDate: futureDate(2, 7),
    endDate: futureDate(2, 8),
    imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80",
    venueName: "Kurrawa Beach",
    venueAddress: "Old Burleigh Rd, Broadbeach QLD 4218",
    city: "Gold Coast",
    state: "QLD",
    category: "COMMUNITY" as const,
    tags: ["yoga", "free", "beach", "wellness", "community"],
    isFree: true,
    source: "seed",
    sourceId: "seed-016",
  },
  {
    name: "Dracula's Cabaret Restaurant",
    description:
      "A night of gothic theatre, comedy, burlesque, and a 3-course dinner at Australia's longest-running cabaret. Prepare for scares, laughs, and surprises in this immersive dining experience.",
    startDate: futureDate(11, 19),
    endDate: futureDate(11, 23),
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    url: "https://draculas.com.au",
    venueName: "Dracula's Gold Coast",
    venueAddress: "1 Hooker Blvd, Broadbeach QLD 4218",
    city: "Gold Coast",
    state: "QLD",
    category: "THEATRE" as const,
    tags: ["cabaret", "dinner show", "comedy", "theatre"],
    isFree: false,
    priceMin: 99,
    priceMax: 169,
    ticketUrl: "https://draculas.com.au/gold-coast",
    source: "seed",
    sourceId: "seed-017",
  },
  {
    name: "Tamborine Mountain Wine & Cheese Trail",
    description:
      "Self-guided tour of Tamborine Mountain's boutique wineries, distilleries, and cheese makers. Pick up your trail map at the information centre and explore at your own pace.",
    startDate: futureDate(4, 10),
    endDate: futureDate(4, 17),
    imageUrl: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80",
    url: "https://visittamborinemountain.com.au",
    venueName: "Tamborine Mountain",
    venueAddress: "Gallery Walk, Tamborine Mountain QLD 4272",
    city: "Gold Coast",
    state: "QLD",
    category: "FOOD_DRINK" as const,
    tags: ["wine", "cheese", "hinterland", "self-guided"],
    isFree: true,
    source: "seed",
    sourceId: "seed-018",
  },
];

async function main() {
  console.log("Seeding Eventure database with Gold Coast events...");

  for (const event of events) {
    const slug = slugify(event.name);
    await prisma.event.upsert({
      where: { source_sourceId: { source: event.source, sourceId: event.sourceId } },
      update: { ...event, slug, status: "published", lastScrapedAt: new Date() },
      create: { ...event, slug, status: "published", lastScrapedAt: new Date() },
    });
    console.log(`  + ${event.name}`);
  }

  console.log(`\nSeeded ${events.length} events.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
